image: gitpod/workspace-node:latest

ports:
- port: 9000
- port: 4000

tasks:
  - name: Start
    before: npm i -g @quasar/cli
    init: yarn
    command: quasar dev
    openMode: split-left

vscode:
  extensions:
    - TabNine.tabnine-vscode
    - EditorConfig.EditorConfig
    - dbaeumer.vscode-eslint
    - wix.vscode-import-cost
    - Vue.volar
    - gamunu.vscode-yarn
    - wayou.vscode-todo-highlight
