image: gitpod/workspace-node:latest

ports:
- port: 9000
- port: 4000

tasks:
  - name: Start
    before: npm i -g @quasar/cli
    init: yarn
    command: quasar dev
    openMode: split-left

  - name: Restore .env file
    command: |
      if [ -f .env ]; then
        # If this workspace already has a .env, don't override it
        echo "Found .env in workspace"
      else
        if [ -z "${DOTENV}" ]; then
          # There is no $DOTENV from a previous workspace. Default to the example .env
          echo "Setting example .env"
          cp .env.example .env
        else
          # After making changes to .env, run this line to persist it to $DOTENV
          #   gp env DOTENV="$(base64 .env | tr -d '\n')"
          #
          # Environment variables set this way are shared between all your workspaces for this repo
          echo "Restoring .env from Gitpod"
          echo "${DOTENV}" | base64 -d > .env
        fi
      fi

vscode:
  extensions:
    - TabNine.tabnine-vscode
    - EditorConfig.EditorConfig
    - dbaeumer.vscode-eslint
    - wix.vscode-import-cost
    - Vue.volar
    - gamunu.vscode-yarn
    - wayou.vscode-todo-highlight
