name: Deploy to Production

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Setup SSH keys
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts

      - name: Deploy
        env:
          VPS_USER: ${{ vars.VPS_USER }}
          VPS_IP_ADDRESS: ${{ vars.VPS_IP_ADDRESS }}
          VPS_PATH: ${{ vars.VPS_PATH }}
          DATABASE_URL: ${{ vars.DATABASE_URL }}
          NUXT_SENDGRID_API_KEY: ${{ secrets.NUXT_SENDGRID_API_KEY }}
          NUXT_RECAPTCHA_SECRET_KEY: ${{ secrets.NUXT_RECAPTCHA_SECRET_KEY }}
          NUXT_PUBLIC_RECAPTCHA_SITE_KEY: ${{ secrets.NUXT_PUBLIC_RECAPTCHA_SITE_KEY }}
        run: |
          ssh -tt "$VPS_USER@$VPS_IP_ADDRESS" "bash -i <<EOF
          cd \"$VPS_PATH\"
          git checkout main
          git pull --rebase
          pnpm install
          export DATABASE_URL=\"$DATABASE_URL\"
          npx prisma generate
          npx prisma migrate deploy
          unset DATABASE_URL
          rm .env
          cp .env.sample .env
          sed -i \"s|{{ DATABASE_URL }}|${DATABASE_URL//\//\\/}|g\" .env
          sed -i \"s|{{ NUXT_SENDGRID_API_KEY }}|${NUXT_SENDGRID_API_KEY//\//\\/}|g\" .env
          sed -i \"s|{{ NUXT_RECAPTCHA_SECRET_KEY }}|${NUXT_RECAPTCHA_SECRET_KEY//\//\\/}|g\" .env
          sed -i \"s|{{ NUXT_PUBLIC_RECAPTCHA_SITE_KEY }}|${NUXT_PUBLIC_RECAPTCHA_SITE_KEY//\//\\/}|g\" .env
          pnpm build
          pm2 delete alvasori
          pm2 start ecosystem.config.cjs --env production
          pm2 save
          EOF"