name: Deploy to Stage

on:
  workflow_dispatch:
  push:
    branches:
      - stage

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: stage

    steps:
      - name: Setup SSH keys
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts

      - name: Deploy
        env:
          VPS_USER: ${{ vars.VPS_USER }}
          VPS_IP_ADDRESS: ${{ vars.VPS_IP_ADDRESS }}
          VPS_PATH: ${{ vars.VPS_PATH }}
        run: ssh -t "$VPS_USER@$VPS_IP_ADDRESS" "cd \"$VPS_PATH\" && git pull --rebase && bash -i .server/stage/build.sh"
