name: Deploy to Stage

on:
  workflow_dispatch:
  push:
    branches:
      - stage  # or the branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: stage

    steps:
      - name: Setup SSH keys
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts

      - name: Deploy
        env:
          VPS_USER: ${{ vars.VPS_USER }}
          VPS_IP_ADDRESS: ${{ vars.VPS_IP_ADDRESS }}
          VPS_PATH: ${{ vars.VPS_PATH }}
        run: ssh $VPS_USER@$VPS_IP_ADDRESS 'bash -lc "cd $VPS_PATH && ./.server/stage/build.sh"'
